services:
  uniconnect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./UniConnect.API/uniconnect.db:/app/uniconnect.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
